package com.dev.ATSapp.Enums;

public enum InterviewRounds {
    
    APTITUDE,
    GROUP_DISCUSSION,
    TECHNICAL_ROUND1,
    TECHNICAL_ROUND2,
    TECHNICAL_ROUND3,
    TECHNICAL_ROUND4,
    TECHNICAL_ROUND5,
    SYSTEM_DESIGN_ROUND,
    CODING_CHALLENGE,
    PAIR_PROGRAMMING,
    MANAGERIAL_ROUND1,
    MANAGERIAL_ROUND2,
    LEADERSHIP_DISCUSSION,
    HR1,
    HR2,
    FINAL_DISCUSSION
}