package com.dev.ATSapp.Enums;

public enum Department {
    HUMAN_RESOURCES,
    FINANCE_AND_ACCOUNTING,
    SALES_AND_BUSINESS_DEVELOPMENT,
    MARKETING_ADVERTISING,
    CUSTOMER_SUPPORT_AND_SERVICE,
    INFORMATION_TECHNOLOGY,
    ENGINEERING_AND_PRODUCT_DEVELOPMENT,
    OPERATIONS_AND_LOGISTICS,
    RESEARCH_AND_DEVELOPMENT,
    LEGAL_AND_COMPLIANCE,
    PROCUREMENT_AND_SUPPLY_CHAIN,
    QUALITY_ASSURANCE,
    PUBLIC_RELATIONS_AND_COMMUNICATIONS,
    EXECUTIVE_MANAGEMENT,
    STRATEGY_AND_PLANNING;
}
